import { PupoLocation } from "@/types"
import { getDatabase } from "./database"

export async function getAllPupi(): Promise<PupoLocation[]> {
  const db = getDatabase()
  try {
    return await db.getAllPupi()
  } catch (error) {
    console.error("Error reading pupi data:", error)
    return []
  }
}

export async function getPupoById(
  id: number
): Promise<PupoLocation | undefined> {
  const db = getDatabase()
  try {
    return await db.getPupoById(id)
  } catch (error) {
    console.error("Error reading pupo data:", error)
    return undefined
  }
}

export async function createPupo(
  pupo: Omit<PupoLocation, "id">
): Promise<PupoLocation> {
  const db = getDatabase()

  return await db.createPupo({ ...pupo, id: 0 }) // ID will be generated by database
}

export async function updatePupo(
  id: number,
  updates: Partial<Omit<PupoLocation, "id">>
): Promise<PupoLocation | null> {
  const db = getDatabase()
  return await db.updatePupo(id, updates)
}

export async function deletePupo(id: number): Promise<boolean> {
  const db = getDatabase()
  return await db.deletePupo(id)
}

export async function bulkImportPupi(
  pupi: Omit<PupoLocation, "id">[]
): Promise<{ success: number; failed: number; errors: string[] }> {
  let success = 0
  let failed = 0
  const errors: string[] = []

  for (const pupo of pupi) {
    try {
      await createPupo(pupo)
      success++
    } catch (error) {
      failed++
      const errorMessage =
        error instanceof Error ? error.message : String(error)
      errors.push(`Failed to import ${pupo.name}: ${errorMessage}`)
    }
  }

  return { success, failed, errors }
}

// Vote management
export async function addVote(
  userId: string,
  pupoId: number
): Promise<void> {
  const db = getDatabase()
  try {
    await db.addVote(userId, pupoId)
  } catch (error) {
    console.error("Error adding vote:", error)
    throw error
  }
}

export async function removeVote(
  userId: string,
  pupoId: number
): Promise<void> {
  const db = getDatabase()
  try {
    await db.removeVote(userId, pupoId)
  } catch (error) {
    console.error("Error removing vote:", error)
    throw error
  }
}

export async function getUserVotes(userId: string): Promise<number[]> {
  const db = getDatabase()
  try {
    return await db.getUserVotes(userId)
  } catch (error) {
    console.error("Error getting user votes:", error)
    return []
  }
}

export async function getVoteCounts(): Promise<Record<number, number>> {
  const db = getDatabase()
  try {
    return await db.getVoteCounts()
  } catch (error) {
    console.error("Error getting vote counts:", error)
    return {}
  }
}
