import { PupoLocation } from "@/types"
import { getDatabase, isPostgreSQL } from "./database"

export async function getAllPupi(): Promise<PupoLocation[]> {
  const db = getDatabase()
  try {
    if (isPostgreSQL(db)) {
      return await db.getAllPupiAsync()
    } else {
      return db.getAllPupi()
    }
  } catch (error) {
    console.error("Error reading pupi data:", error)
    return []
  }
}

export async function getPupoById(
  id: number
): Promise<PupoLocation | undefined> {
  const db = getDatabase()
  try {
    if (isPostgreSQL(db)) {
      return await db.getPupoByIdAsync(id)
    } else {
      return db.getPupoById(id)
    }
  } catch (error) {
    console.error("Error reading pupo data:", error)
    return undefined
  }
}

export async function createPupo(
  pupo: Omit<PupoLocation, "id">
): Promise<PupoLocation> {
  const db = getDatabase()

  if (isPostgreSQL(db)) {
    return await db.createPupoAsync({ ...pupo, id: 0 }) // ID will be generated by database
  } else {
    return db.createPupo({ ...pupo, id: 0 }) // ID will be generated by database
  }
}

export async function updatePupo(
  id: number,
  updates: Partial<Omit<PupoLocation, "id">>
): Promise<PupoLocation | null> {
  const db = getDatabase()
  if (isPostgreSQL(db)) {
    return await db.updatePupoAsync(id, updates)
  } else {
    return db.updatePupo(id, updates)
  }
}

export async function deletePupo(id: number): Promise<boolean> {
  const db = getDatabase()
  if (isPostgreSQL(db)) {
    return await db.deletePupoAsync(id)
  } else {
    return db.deletePupo(id)
  }
}

export async function bulkImportPupi(
  pupi: Omit<PupoLocation, "id">[]
): Promise<{ success: number; failed: number; errors: string[] }> {
  let success = 0
  let failed = 0
  const errors: string[] = []

  for (const pupo of pupi) {
    try {
      await createPupo(pupo)
      success++
    } catch (error) {
      failed++
      const errorMessage = error instanceof Error ? error.message : String(error)
      errors.push(`Failed to import ${pupo.name}: ${errorMessage}`)
    }
  }

  return { success, failed, errors }
}
